# Generated by Django 5.2.5 on 2025-09-05 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_received',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tiempo total recibido de otros usuarios', verbose_name='Tiempo recibido'),
        ),
        migrations.AddField(
            model_name='user',
            name='time_sent',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tiempo total ofrecido a otros usuarios', verbose_name='Tiempo enviado'),
        ),
    ]
