# Generated by Django 5.2.5 on 2025-09-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_time_received_user_time_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles/default_user.webp', null=True, upload_to='profiles'),
        ),
    ]
