# Generated by Django 5.2.5 on 2025-09-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(max_length=500, verbose_name='Descripción')),
                ('duration', models.CharField(max_length=50, verbose_name='Duración')),
                ('is_online', models.BooleanField(default=False, verbose_name='Servicio online')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('status', models.CharField(default='Disponible', max_length=50, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
                'db_table': 'offers',
            },
        ),
    ]
