# Generated by Django 5.2.5 on 2025-09-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='status',
        ),
    ]
