# Generated by Django 5.2.5 on 2025-09-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_offer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration',
            field=models.DurationField(help_text='Duración del servicio en horas y minutos', verbose_name='Duración'),
        ),
    ]
