# Generated by Django 5.2.5 on 2025-09-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_alter_offer_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, default='offers/default.webp', null=True, upload_to='offers', verbose_name='Imagen'),
        ),
    ]
